### ISSUE TITLE
Rollback link appears on non wp.org plugins

### ISSUE THREAD

**Issue by scottopolis** [WordImpress/WP-Rollback#14]
Awesome plugin guys!

This is only supposed to work with .org plugins, but the rollback link appears on my non .org plugins. It only appears if they need an update, it disappears when they are updated. See image.
![screen shot 2015-05-19 at 3 09 58 pm](https://cloud.githubusercontent.com/assets/5324977/7715077/52325a80-fe39-11e4-9843-a0934430ef58.png)

Other than that, love the plugin!

**Comment by mathetos** [comment]
We tested it with a lot of premium plugins and didn't see that crop up. Can you paste the plugin header here so we can take a look?

**Comment by scottopolis** [comment]
Hey Matt, I'm using the EDD plugin updater: http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins

Not sure what the header will do for you?

**Comment by mathetos** [comment]
Don't you have a readme.txt file with header information in it? I have a feeling it coincides with a Repo plugin name somehow. We use the EDD license updater as well and tested against that, so there's gotta be something else going on.

**Comment by DevinWalker** [comment]
I think I know what's going on here...

**Comment by DevinWalker** [comment]
Thanks for reporting this @scottopolis - it's now been fixed and rolled out to wp.org 

Now... how about a plugin review :+1:  https://wordpress.org/support/view/plugin-reviews/wp-rollback

:)

**Comment by scottopolis** [comment]
Awesome, thanks Devin!
