### ISSUE TITLE
Feature Suggestions - 'Reinstall Current' Text and 'Bulk Reinstall'

### ISSUE THREAD

**Issue by VR51** [WordImpress/WP-Rollback#21]
Carried over from my WordPress plugin review.

Please add **(reinstall)** text next to the currently installed version of a plugin or theme. I didn't realise currently installed versions could be reinstalled until @mathetos told me they could earlier today in the WP forums.

Please add a **bulk reinstall** option. When I clean up malware infected sites I reinstall clean versions of all plugins and themes; a bulk reinstall option would save developers a ton of mouse clicks and button presses. I am assuming the reinstaller deletes each plugin's directory before reinstallation.

Question: Is there an option to roll back WordPress versions? Had a quick look under Dashboard > Updates but could see a button for this. Would be useful for plugin developers who want to test WP compatibility.

Love the plugin. Thank you.

**Comment by DevinWalker** [comment]
Cool suggestions thanks

**Comment by DevinWalker** [comment]
Just wanted to give an update here that we won't be supporting WP core rollbacks. There's just too much stuff that can go wrong if you rollback to version 1.0 of WordPress, etc.

**Comment by DevinWalker** [comment]
WP Rollback adds an "Installed version" text next to the currently installed version: 

![2018-06-01_09-21-31](https://user-images.githubusercontent.com/1571635/40851765-3632f50c-657d-11e8-89ac-469089d4e0c8.png)

I believe this should suffice for this option.

Also the plugin won't be supporting bulk rollbacks in the future. That's best left for backup plugins.
