### ISSUE TITLE
Add Multisite Support for Rolling Back

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/WP-Rollback#22]
It's been brought up that multisite doesn't work as expected: https://wordpress.org/support/topic/cannot-rollback-from-network-dashboard?replies=6

We should add support for WP Multisite

**Comment by icryptic** [comment]
I was able to update the plugin to work on Multisite, but only the plugins portion. Haven't been able to get the themes bit figured out.

**Comment by andreafalzetti** [comment]
Hi guys, is this already available? ( I saw commit 2db3ca) We have a large multisite and I have installed and network activated __WP Rollback__ but the rollback button doesn't appear.

**Comment by DevinWalker** [comment]
We haven't released it yet. Did you install from the repo or Github?

**Comment by andreafalzetti** [comment]
No, I have installed from the WP repository. Shall I give a try to the version on GitHub or wait for a stable release?

**Comment by DevinWalker** [comment]
It hasn't been tested yet, so I'd wait until it's released on WP.org for stable.
