### ISSUE TITLE
Consider having the Save Button be fixed at the bottom

### ISSUE THREAD

**Issue by mathetos** [WordImpress/WP-Rollback#23]
Some plugins have A LOT of versions which makes the list very long and the save button very far away. Perhaps we could fix it to the bottom of the screen for better ease of use.

**Comment by icryptic** [comment]
![download](https://cloud.githubusercontent.com/assets/5396272/12186214/ca1d6cb6-b55d-11e5-9cf5-d63e9b7b84d1.png)

I updated the plugin to show both the rollback and cancel button in a fixed right position. They continue to stay in that position when the users scrolls down the page.

https://github.com/icryptic/WP-Rollback
