### ISSUE TITLE
There's no rollback button for any theme

### ISSUE THREAD

**Issue by c00** [WordImpress/WP-Rollback#24]
I'm using the latest version of WordPress, 4.4.2. I've just installed wp Rollback as I need to get a previous version of a theme. However, this theme and any other theme I have installed doesn't have a Rollback button in the details screen.

The theme in this case is [Coller] (https://wordpress.org/themes/coller/). Am I missing something?

quick edit: I do see there's a message in the bottom left "No Rollback Available: This is a non-WordPress.org theme." however, that's not true, as you can see from the link above.

**Comment by DevinWalker** [comment]
It works for me: 
![2-8-2016 9-57-29 am](https://cloud.githubusercontent.com/assets/1571635/12894225/665b693e-ce4a-11e5-8e94-02062ee92aab.png)

For support request please user this forum: http://wordpress.org/support/plugin/wp-rollback 

Thanks for using the plugin!

**Comment by mathetos** [comment]
Hi @c00 Like Devin said, we handle support at the form. There is a support ticket over there that references a similar problem and the user reports a solution as well. Check it out here:
https://wordpress.org/support/topic/themes-cant-be-rolled-back

Thanks!
