### ISSUE TITLE
wp-cli support

### ISSUE THREAD

**Issue by COLABORATI** [WordImpress/WP-Rollback#26]
Hi, does this plugin provide support for wp-cli? 
If not, then this should be a feature request.
Thanks!

**Comment by DevinWalker** [comment]
WP cli already has a rollback doesn't it?

**Comment by mathetos** [comment]
@shawnhooper Does WP CLI already have a rollback function built-in?

**Comment by shawnhooper** [comment]
@mathetos Yes it does. 

For WordPress Core, you can run `wp core download --version=3.8` to download version 3.8, or example. 

For themes, run `wp theme install --version=X` or `wp theme update --version=X` to install version X. 

For plugins, run `wp plugin install --version=X` or `wp plugin update --version=X` to install version X. 

It doesn't look like you can get a list of available version numbers through CLI. You could retrieve these from the corresponding WordPress.org pages for the plugin or theme.

**Comment by mathetos** [comment]
So, we could feasibly extend WP CLI in Rollback and do something like `wp rollback plugin versions` and get a list of available versions, then `wp plugin install --version=X` so the only utility with Rollback would be adding the ability to see all the plugin versions.

**Comment by DevinWalker** [comment]
I'd rather support WP-CLI and add the ability to list past plugin versions there than include our own CLI. Closing this one out.
