### ISSUE TITLE
If plugin is network activated limit rollbacks to only network admin screen

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/WP-Rollback#33]
## Issue Overview

If the plugin is activated network wide, rollbacks should only be able to take place on the main network settings plugin page. 

Imagine you have a network of 100+ sites. You wouldn't want an admin of a specific site to be able to rollback a plugin that would affect the entire network. 

@mathetos @drrobotnik what do you think?

**Comment by drrobotnik** [comment]
Good catch. It looks like there is a Networks Settings option to enable/disable administrators the ability manage plugins which in my case was disabled by default so to me it looked like only Network Admins would see it. Since this is not the case +1, should fix.

**Comment by mathetos** [comment]
Agreed. Super Admins only.

**Comment by DevinWalker** [comment]
Another weird thing about multisite is that installed themes are displayed differently than single sites. They are using wp list table like plugins:  

![2017-07-11_19-46-28](https://user-images.githubusercontent.com/1571635/28099487-b7236cca-6671-11e7-9051-b15976773622.png)

If we're going to fully limit rollbacks to the network admin section we will need to support rollbacks for themes similarly to how we do plugins. Shouldn't be difficult.

**Comment by DevinWalker** [comment]
I got it working for themes w/ the multisite list table:

![Uploading 2017-07-11_21-58-24.gif…]()
