### ISSUE TITLE
Update header graphic

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/WP-Rollback#37]
It's outdated and looks like 💩

**Comment by DevinWalker** [comment]
What do you guys think of this?

## New banner

![2017-07-12_17-48-11](https://user-images.githubusercontent.com/1571635/28145867-7704569a-672a-11e7-9cde-0d9083e15421.png)

## Preview on WP.org

![2017-07-12_17-48-24](https://user-images.githubusercontent.com/1571635/28145870-7cdc1eea-672a-11e7-98ee-d27c5f344f1b.png)

Don't mind the green text, that was a mistake.

**Comment by mathetos** [comment]
@DevinWalker LOVE IT!

**Comment by DevinWalker** [comment]
Cool, works for me.
