### ISSUE TITLE
Sometimes invalid plugin header warning

### ISSUE THREAD

**Issue by Shelob9** [WordImpress/WP-Rollback#39]
## Issue Overview
Plugin doesn't have a valid plugin header warning when plugin does have a valid header.

## Expected Behavior
Matt makes me a taco.

## Current Behavior
I rolled back on a plugin, got "Plugin doesn't have a valid plugin header" wp_die. Manually activated plugin (the version WP Rollback did) works fine. 

## Steps to Reproduce (for bugs)
Has happened to me a few times on my WPEngine site, but I can't figure out how to make it reliably happen. Sorry.

**Comment by mathetos** [comment]
Which plugin did this happen with? Caldera Forms?

**Comment by Shelob9** [comment]
Yes. Caldera Forms. Happened to me rolling up from Caldera Forms 1.5.3.1 to
1.5.4-b-3. Was on JoshPess.net. Worked fine when I activated the WP
Rollback installed plugin.


On Aug 3, 2017 12:20 PM, "Matt Cromwell" <notifications@github.com> wrote:

Which plugin did this happen with? Caldera Forms?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WordImpress/WP-Rollback/issues/39#issuecomment-320018746>,
or mute the thread

**Comment by DevinWalker** [comment]
I'm unable to reliably reproduce and haven't heard reports of this on WP.org - closing until reliably reproduced or widely reported.
