### ISSUE TITLE
AJAX plugin Rollback

### ISSUE THREAD

**Issue by drrobotnik** [WordImpress/WP-Rollback#4]
WP4.2 added new function wp_ajax_update_plugin();

We could do exactly the same thing, change line 2914 to reference our downgrade class.

**Comment by DevinWalker** [comment]
Change line 2914 where?

**Comment by drrobotnik** [comment]
in our version of wp_ajax_update_plugin();

Ref:
https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/ajax-actions.php#L2914

**Comment by DevinWalker** [comment]
I like how it's working now with the old updater method. AJAX would be fancy pants but not needed.
