### ISSUE TITLE
Must Have option to roll back the WordPress as Well

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/WP-Rollback#40]
## Issue Overview
There must be an option to roll back the WordPress as Well 

## Expected Behavior
Did not find any option to roll the WordPress as well

## Current Behavior
No Option

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
We considered this but ultimately decided against it as it's pretty dangerous. Plus, this may not be agreeable to the WP core contributors and plugin repo mods.

**Comment by raftaar1191** [comment]
Okay
Thanks @DevinWalker for the clarification
