### ISSUE TITLE
Feature Suggestion: Provide dates of plugin releases

### ISSUE THREAD

**Issue by pmsteil** [WordImpress/WP-Rollback#41]
## Issue Overview
When rolling back a plugin, it would be very helpful to know the date of each plugins release.  Example:  We recently updated about 10 plugins. One of them is causing a problem on our site.  We didn't have WP Rollback installed.  I have it installed now.  If I could see the dates of the plugins that I can choose to rollback to it would greatly help figure out which plugins I updated recently.

Thanks!

**Comment by pmsteil** [comment]
Ok I did just see where I can rollover and see the Changelog, lol... still, it would be cool to display the date next to each release if that is easy to get.

**Comment by pmsteil** [comment]
And if the last updated date is something that is available, it would be super helpful to see that date on the wp-admin/plugins.php page itself.  

Thanks to your plugin we DID fix the problem we were having caused by a plugin, thanks!!!!

**Comment by DevinWalker** [comment]
@pmsteil I'll have to see if we can get the date of the SVN tag. I'm not sure off the top of my head.

**Comment by DevinWalker** [comment]
It doesn't appear that we can obtain the date of the SVN tag easily. This is what where we get the tags from: http://plugins.svn.wordpress.org/give/tags/

 The best bet is to check the change log like you said and if the author adds the date of the release there, but it's up to the author to add that date.
