### ISSUE TITLE
Implement WP Time Capsule Upsell for Backups

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/WP-Rollback#43]
## Issue Overview

WP Time Capsule is our preferred backup solution. We should to implement an upsell throughout the plugin with a banner on the side and of the version number and a "Backup" button that goes to the WP Time Capsule page.

Affiliate link: 

`https://wptimecapsule.com/index.php?partner=impress`

**Comment by thamaraiselvam** [comment]
Close this issue since pull request #44 created for this.
