### ISSUE TITLE
Integrate Changelog somehow

### ISSUE THREAD

**Issue by mathetos** [WordImpress/WP-Rollback#7]
I'll dig into this a little, but it'd be nice to reflect the changelog per version if possible. If that's overly complex then I might just give an easy modal popup of the whole changelog as a reference. This might not be possible at all with Themes, but should be within the realm of feasibility with plugins.

**Comment by DevinWalker** [comment]
@mathetos for plugins only?

**Comment by mathetos** [comment]
Themes are going to have changelogs too pretty soon. So we might as well support both.
